### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by tanujdhiman** [cs-MohamedAyman/Data-Structures#1]
Hey 
Can you please tell me about the difference between stack implement with array and stack implement with linked list ?

Thanks

**Comment by cs-MohamedAyman** [comment]
Kindly find the lectures below
[4] Stack Linked List Based
https://github.com/cs-MohamedAyman/Data-Structures/blob/master/Lecture-04-Stack/%5B4%5D%20Stack%20Linked%20List%20Based.pdf
[4] Stack Array Based
https://github.com/cs-MohamedAyman/Data-Structures/blob/master/Lecture-04-Stack/%5B4%5D%20Stack%20Array%20Based.pdf
