### ISSUE TITLE
Add the skip list data structure

### ISSUE THREAD

**Issue by TawfikYasser** [cs-MohamedAyman/Data-Structures#2]
Hello Dear @cs-MohamedAyman , I’m opening this issue to say that
I want to add **Skip List** Data Structure to this repository.

If you don’t have any problem please tell me and i will open PR to add it.

Thanks.

**Comment by cs-MohamedAyman** [comment]
Please do that in the advanced data structures repo.

**Comment by TawfikYasser** [comment]
Okay, Thanks i will do that.
